### ISSUE TITLE
Non SQL expressions

### ISSUE THREAD

**Issue by ryanhamilton** [kelsin/mysql-mimic#57]
Hi,

I'm using mysql-mimic to "query" non SQL data sources. I've had to hack the mysql-mimic source code to allow this as expression due to expression being required (code snippets below). I'm likely to also want to customize or add more return types than you may support. 

1. Is this a use-case currently supported I just couldn't find?
2. Or would you be open to having a PR (advice or guidance would be much appreciated as I'm quite new to python).

session.py I added an if
```
        elif q.expression != None:
            q.expression.transform(_transform, copy=False)
```

```
    async def _set_var_middleware(self, q: Query) -> AllowedResult:
        """Handles any SET_VAR hints, which set system variables for a single statement"""
        hints = q.expression.find_all(exp.Hint) if q.expression != None else []
```

and skipped parsing ``exps = self._parse(sql)``

**Comment by barakalon** [comment]
You can extend `BaseSession` directly. In Java parlance, that's like the interface while `Session` is like an abstract class.

For more return types, see `AllowedResult` and `ResultColumn` in [results.py](https://github.com/kelsin/mysql-mimic/blob/main/mysql_mimic/results.py). You can explicitly set the MySQL column types instead of letting mysql-mimic infer them.

**Comment by ryanhamilton** [comment]
Very useful guidance, thanks.
