### ISSUE TITLE
column mismatch issue if table name prefix are match with another table

### ISSUE THREAD

**Issue by TathagatRaj** [kelsin/mysql-mimic#59]
"Table 1": {
            "legal_name": "text",
            "short_codes": "text"
        },
        "Table 1 2": {
            "id": "text",
            "code": "text",
            "name": "text",
            "location_id": "text",
            "address": "text",
            "fax": "text"
        }
        
This is my schema configuration for table when I clicked on "table 1" that time I got "Table 1 2" columns in query with table1. its happening bcz both table prefix are match. can you please help here to use only specific table and not using prefix table cols

**Comment by barakalon** [comment]
@TathagatRaj again, I think you're working with some kind of Excel integration that I am not aware of. 

From my tests use the MySQL CLI, this schema works fine. I'm not sure if the issue is coming from some other usage pattern or from the Excel integration, outside the control of MySQL-Mimic. I'll need a minimally reproducible example before I can help.
